export const HANDLE_ADD_PRODUCT = 'HANDLE_ADD_PRODUCT';
export const HANDLE_REMOVE_PRODUCT = 'HANDLE_REMOVE_PRODUCT';
export const HANDLE_ITEM_CHANGE = 'HANDLE_ITEM_CHANGE';
export const HANDLE_WAREHOUSE_CHANGE = 'HANDLE_WAREHOUSE_CHANGE';
export const HANDLE_LOT_FETCH_SUCCESS = 'HANDLE_LOT_FETCH_SUCCESS';
export const HANDLE_LOT_FETCH_FAILURE = 'HANDLE_LOT_FETCH_FAILURE';
export const HANDLE_PRODUCT_ERROR = 'HANDLE_PRODUCT_ERROR';